spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appx
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  cloud:
    openfeign:
      client:
        config:
          getOrganizationKid:
            url: http://localhost:8080/kids
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: emil.moise@gmail.com
    password: mstegqstwmytflcg
    port: '587'
